### ISSUE TITLE
peoples的status属性0-5分别表示什么呢

### ISSUE THREAD

**Issue by zw1068** [y1han/virus-simulation#1]

**Comment by y1han** [comment]
不好意思，在改过项目结构以后之前的注释也不小心删掉了，现在再添加上去
People Status:
[0]Susceptible, 易感染
[1]Exposed, 潜伏期
[2]Infective, 感染期
[3]Hospitalized, 住院
[4]Recovered, 免疫期
[5]Dead, 死亡

**Comment by zw1068** [comment]
谢啦。
另外再提一个问题，潜伏期过后，peoples会从Exposed变为Recovered，从图像效果上来看，会与真正的从Infective&Hospitalized变为Recovered造成混淆，请教，为何不是从Exposed变为Susceptible？

**Comment by y1han** [comment]
是这样的，Exposed是潜伏期（黄色），Susceptible（白色）是易感人群，未感染。Exposed在潜伏期后是变成Infective（红色），此时具有感染性。之后就是Infective被住院了，进入Hospitalized状态。最后出院时变成Recovered（绿色）。Recovered在免疫期过去后会重新变为Susceptible（白色）。Infective和Hospitalized时都有几率死亡。
can_exposed_infect参数可以调整Exposed（黄色）能否传染
recovered_included参数可以调整出院后是否有免疫期

因此Exposed应该不存在变为Recovered和Susceptible的情况
这几种类型的名称我都是参考SEIR模型里各个类的

**Comment by zw1068** [comment]
> 
> 
> 是这样的，Exposed是潜伏期（黄色），Susceptible（白色）是易感人群，未感染。Exposed在潜伏期后是变成Infective（红色），此时具有感染性。之后就是Infective被住院了，进入Hospitalized状态。最后出院时变成Recovered（绿色）。Recovered在免疫期过去后会重新变为Susceptible（白色）。Infective和Hospitalized时都有几率死亡。
> can_exposed_infect参数可以调整Exposed（黄色）能否传染
> recovered_included参数可以调整出院后是否有免疫期
> 
> 因此Exposed应该不存在变为Recovered和Susceptible的情况
> 这几种类型的名称我都是参考SEIR模型里各个类的

ok懂了，我之前的理解是，潜伏期是针对密切接触者，14天后可能被感染也可能不被感染。
谢谢！
