### ISSUE TITLE
请问致死率和治愈率是怎么给定的

### ISSUE THREAD

**Issue by zw1068** [y1han/virus-simulation#2]
请教：
看到代码中将致死率设置为
DEATH_RATE = 0.01/(CURE_TIME+10*HOSPITAL_RECEIVE_TIME) #每日死亡概率
请问原因是什么呢，而且为什么是每日死亡率，而不是平均死亡率？
还有治愈率是如何设置的？

**Comment by y1han** [comment]
因为在我personpool.py里update函数的设定中，Infective状态下死亡率是Hospitalized状态下死亡率的10倍。
是否死亡是由随机数每日和DEATH_RATE进行比对的，所以订作每日死亡率（概率）更为恰当。如果要进行仿真模拟的话，因为有各种随机数的因素，因此比较难以确定总量。
治愈时间是通过CURE_TIME进行调整的，因为除了死亡以外就是治愈，因此在这里没有专门调整治愈率的参数。
