### ISSUE TITLE
图片显示不出

### ISSUE THREAD

**Issue by Ren-Thomas** [y1han/virus-simulation#4]
UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  self.figure.tight_layout()

**Comment by y1han** [comment]
麻烦提供一下使用的平台、系统和python版本可以嘛？

根据我目前在[其他issue](https://github.com/siavashk/pycpd/issues/30)上找到的可能情况，在使用Pycharm的时候会出现兼容性的问题：报错原因在于plt.tight_layout在该IDE中不能顺利工作。
此时通过取消勾选工具栏中 **File > Settings > Tools > Python Scientific > show plots in tool window** 的选项是一种潜在的方案。也可尝试用其他编辑器运行看看问题是否依旧存在。

若是其他的情况，烦请详细说明，谢谢！

**Comment by Ren-Thomas** [comment]
解决了，tql，多谢

**Comment by y1han** [comment]
哈哈，没事的
